version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - unconvert
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fission/fission
        - github.com/fission/keda-connectors
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
