pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - label!=hold-off-merging
    actions:
      merge:
        method: squash
