name: Keda Setup

description: Setup Kind and Keda

runs:
  using: "composite"
  steps:
    - name: Setup Kind cluster
      uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
      with:
        node_image: kindest/node:v1.23.17
        version: v0.20.0
        cluster_name: kind

    - name: Helm installation
      uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: v3.13.0

    - name: Install Keda
      shell: bash
      run: |
        kubectl create namespace keda
        helm repo add kedacore https://kedacore.github.io/charts
        helm repo update
        helm install keda kedacore/keda --namespace keda --version 2.12.0

    - name: Setup Ko
      uses: ko-build/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa # v0.6
      env:
        KO_DOCKER_REPO: kind.local

    - name: Run local http server
      shell: bash
      run: |
        ko resolve -f test/server/server.yaml | kubectl apply -f -
        kubectl wait pod -l app=http --for=condition=ready --timeout=-1s
