name: Keda Setup

description: Setup Kind and Keda

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: "go.mod"
        cache: true

    - name: Setup Kind cluster
      uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
      with:
        node_image: kindest/node:v1.25.16
        version: v0.23.0
        cluster_name: kind

    - name: Helm installation
      uses: Azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      with:
        version: v3.15.2

    - name: Install Keda
      shell: bash
      run: |
        kubectl create namespace keda
        helm repo add kedacore https://kedacore.github.io/charts
        helm repo update
        helm install keda kedacore/keda --namespace keda --version 2.14.0

    - name: Setup Ko
      uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037 # v0.7
      env:
        KO_DOCKER_REPO: kind.local

    - name: Run local http server
      shell: bash
      run: |
        ko apply -f test/server/server.yaml
        kubectl wait pod -l app=http --for=condition=ready --timeout=-1s
