apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
  namespace: kafka
  labels:
    app: consumer
spec:
  completions: 1
  template:
    spec:
      containers:
      - name: consumer
        image: localhost:5000/consumer:latest
      restartPolicy: Never
  backoffLimit: 0
